# START
runtime: python312
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.95
  max_concurrent_requests: 70
  target_throughput_utilization: 0.70
  max_instances: 1
entrypoint: gunicorn -b 0.0.0.0:8080 app:server
# END